apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  namespace: monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      containers:
      - name: metrics-collector
        image: YOUR_DOCKERHUB_USERNAME/monitoring-collector:latest
        env:
        - name: BACKEND_URL
          value: http://backend:5000
